name: request_easy_loading
description: This package helps you to show loading or progress dialog while sending request to server and it doesn't need context for doing that
version: 1.0.1
homepage: https://github.com/sepehr13494/request_easy_loading

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
